#ifdef BOARD_MASIFI_SENSOR_BREAKOUT
#define PROG_LED_PIN 1
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 0
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
#define SAVE_INTERRUPT_PIN 22
#define KNX_UART_RX_PIN 17
#define KNX_UART_TX_PIN 16
#define HARDWARE_NAME "MASIFI-SMBB-V1"
#endif

#ifdef BOARD_KONNEKTION_TEST
#define PROG_LED_PIN A3
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 38
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
// #define KNX_UART_RX_PIN 0
// #define KNX_UART_TX_PIN 1
#define HARDWARE_NAME "KONNEKTING-TEST"
#endif

#ifdef BOARD_SIRSYDOM_PIPICO_BCU_CONNECTOR
#define PROG_LED_PIN 21
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 22
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
#define SAVE_INTERRUPT_PIN 20
#define KNX_UART_RX_PIN 1
#define KNX_UART_TX_PIN 0
#define HARDWARE_NAME "PiPico_BCU_Connector"
#endif

#ifdef BOARD_SMARTMF_1TE_RP2040
#define PROG_LED_PIN 1
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 0
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
#define SAVE_INTERRUPT_PIN 29
#define KNX_UART_RX_PIN 17
#define KNX_UART_TX_PIN 16
#define HARDWARE_NAME "1TE_RP2040_SmartMF"
#endif

#ifdef BOARD_OPENKNX_REG1_BASE
#define PROG_LED_PIN 2
#define PROG_LED_PIN_ACTIVE_ON HIGH
#define PROG_BUTTON_PIN 7
#define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
#define SAVE_INTERRUPT_PIN 6
// #define INFO_LED_PIN 3
// #define INFO_LED_PIN_ACTIVE_ON HIGH
#define KNX_UART_RX_PIN 1
#define KNX_UART_TX_PIN 0
#define HARDWARE_NAME "OpenKNX_REG1_Base"
#endif